"use client";

import {
  Code2,
  Braces,
  Layout,
  Wind,
  FileCode,
  Database,
  Layers,
  Server,
  Shield,
  Key,
  Lock,
  Container as DockerIcon,
  Cloud,
  Workflow,
  Binary,
  GitBranch,
  Grid3x3,
  Sparkles,
  Leaf,
  Radio,
  Trophy,
  Bot,
  MessageSquare,
  Wand2,
  MousePointer2,
  Cylinder,
  TrainFront,
  Globe,
} from "lucide-react";

export const skillIconMap = {
  python: Code2,
  c: FileCode,
  cpp: Code2,
  javascript: Braces,
  react: Braces,
  nextjs: Layout,
  tailwind: Wind,
  bootstrap: Grid3x3,
  daisyui: Sparkles,
  html: FileCode,
  django: Database,
  drf: Layers,
  node: Server,
  postgres: Database,
  mysql: Database,
  sqlite: Database,
  mongodb: Cylinder,
  jwt: Key,
  oauth: Shield,
  auth: Lock,
  nextauth: Shield,
  docker: DockerIcon,
  vercel: Cloud,
  netlify: Globe,
  render: Cloud,
  railway: TrainFront,
  git: GitBranch,
  cicd: Workflow,
  redis: Database,
  celery: Leaf,
  websocket: Radio,
  cp: Trophy,
  dsa: Binary,
  cursor: MousePointer2,
  claude: Bot,
  chatgpt: MessageSquare,
  gemini: Sparkles,
  copilot: Wand2,
  default: Binary,
};

export function getSkillIcon(iconKey) {
  return skillIconMap[iconKey] || skillIconMap.default;
}
